version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free:19-slim
    container_name: oracle_db
    environment:
      - ORACLE_PASSWORD=Mimidoox123
    ports:
      - "1521:1521"
    restart: always

  backend:
    build: .
    container_name: ticket_manager_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/ORCLCDB
      SPRING_DATASOURCE_USERNAME: SYS as sysdba
      SPRING_DATASOURCE_PASSWORD: Mimidoox123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9090:9090"
    depends_on:
      - oracle-db
